force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/AVR_Attachment_Validation_Rules__c.object-meta.xml
<CustomObject>
    <label>AVR Attachment Validation Rules</label>
    <nameField>
        <displayFormat>AVR-{0000}</displayFormat>
        <label>AVR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <defaultValue>&quot;現在の状態ではこの操作を行えません。取り消し/却下してから操作して下さい。&quot; &amp; BR() &amp;
&quot;This operation can not be performed in the current state. Please cancel / reject it before operation.&quot;</defaultValue>
    <label>Error Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/Excluded_Profile__c.field-meta.xml
<CustomField>
    <fullName>Excluded_Profile__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <inlineHelpText>Name</inlineHelpText>
    <label>Excluded Profile</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/Excluded_Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Excluded_Public_Group__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <inlineHelpText>DeveloperName</inlineHelpText>
    <label>Excluded Public Group</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/Excluded_User__c.field-meta.xml
<CustomField>
    <fullName>Excluded_User__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <inlineHelpText>Username</inlineHelpText>
    <label>Excluded User</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AVR_Attachment_Validation_Rules__c/fields/SOQL_WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>SOQL_WHERE_Clause__c</fullName>
    <label>SOQL WHERE Clause</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AVR_Attachment_Helper.cls
/**
 * @author      nsuhara <na010210dv@gmail.com>
 * @version     1.0
 * @since       2019/01/01
 * @description
 * Support for Salesforce Classic and Lightning Experience.
 */
public without sharing class AVR_Attachment_Helper {

    @TestVisible
    AVR_Attachment_Helper() {
    }

    @TestVisible
    private class CurrentUserInfo {
        @TestVisible String         strProfileAssignment;
        @TestVisible List<String>   lstGroupAssignment;
        @TestVisible String         strUserName;
        CurrentUserInfo() {
            this.lstGroupAssignment = new List<String>();
        }
    }

    static public Map<String, AVR_Attachment_Validation_Rules__c> getValidationRules() {
        Map<String, AVR_Attachment_Validation_Rules__c> mapRules = new Map<String, AVR_Attachment_Validation_Rules__c>();
        for (List<AVR_Attachment_Validation_Rules__c> lstRules : [SELECT Id, SObject__c, SOQL_WHERE_Clause__c, Excluded_Profile__c, Excluded_Public_Group__c, Excluded_User__c, Error_Message__c FROM AVR_Attachment_Validation_Rules__c WHERE IsActive__c = TRUE]) {
            for (AVR_Attachment_Validation_Rules__c r : lstRules) {
                mapRules.put(r.SObject__c, r);
            }
        }
        return mapRules;
    }

    static public Map<String, Map<Id, List<SObject>>> filterAttachments(Map<String, AVR_Attachment_Validation_Rules__c> mapRules, List<SObject> lstObjs, String parentKey) {
        final Set<String> SOBJECTS = new Set<String>(mapRules.keySet());
        Map<String, Map<Id, List<SObject>>> mapObjs = new Map<String, Map<Id, List<SObject>>>();

        for (SObject o : lstObjs) {
            Id parentId = (Id)o.get(parentKey);
            String SObjectName = parentId.getSObjectType().getDescribe().getName();
            if (SOBJECTS.contains(SObjectName)) {
                if (mapObjs.containsKey(SObjectName)) {
                    if (mapObjs.get(SObjectName).containsKey(parentId)) {
                        mapObjs.get(SObjectName).get(parentId).add(o);
                    } else {
                        mapObjs.get(SObjectName).put(parentId, new List<SObject>{o});
                    }
                } else {
                    mapObjs.put(SObjectName, new Map<Id, List<SObject>>{parentId => new List<SObject>{o}});
                }
            }
        }
        return mapObjs;
    }

    static public Void triggerEvent(Map<String, AVR_Attachment_Validation_Rules__c> mapRules, Map<String, Map<Id, List<SObject>>> mapObjs) {
        CurrentUserInfo objCurrentUserInfo = getCurrentUserInfo();
        for (String SObjectName : mapObjs.keySet()) {
            validate(mapRules.get(SObjectName), objCurrentUserInfo, mapObjs.get(SObjectName));
        }
    }

    @TestVisible
    static private CurrentUserInfo getCurrentUserInfo() {
        List<User> lstUsers = [SELECT Id, Username, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
        List<GroupMember> lstMembers = [SELECT Id, Group.DeveloperName FROM GroupMember WHERE UserOrGroupId = :UserInfo.getUserId()];
        CurrentUserInfo objCurrentUserInfo = new CurrentUserInfo();

        objCurrentUserInfo.strProfileAssignment = lstUsers[0].Profile.Name;
        for (GroupMember m : lstMembers) {
            objCurrentUserInfo.lstGroupAssignment.add(m.Group.DeveloperName);
        }
        objCurrentUserInfo.strUserName = lstUsers[0].Username;
        return objCurrentUserInfo;
    }

    @TestVisible
    static private Void validate(AVR_Attachment_Validation_Rules__c objRule, CurrentUserInfo objCurrentUserInfo, Map<Id, List<SObject>> mapObjs) {
        if (!validateUser(objRule, objCurrentUserInfo)) {
            validateAttachment(objRule, mapObjs);
        }
    }

    @TestVisible
    static private Boolean validateUser(AVR_Attachment_Validation_Rules__c objRule, CurrentUserInfo objCurrentUserInfo) {
        Set<String> setExcludedProfiles = new Set<String>(objRule.Excluded_Profile__c.split(';'));
        Set<String> setExcludedGroups = new Set<String>(objRule.Excluded_Public_Group__c.split(';'));
        Set<String> setExcludedUsers = new Set<String>(objRule.Excluded_User__c.split(';'));

        if (setExcludedProfiles.contains(objCurrentUserInfo.strProfileAssignment)) {
            return true;
        }
        for (String g : objCurrentUserInfo.lstGroupAssignment) {
            if (setExcludedGroups.contains(g)) {
                return true;
            }
        }
        if (setExcludedUsers.contains(objCurrentUserInfo.strUserName)) {
            return true;
        }
        return false;
    }

    @TestVisible
    static private Void validateAttachment(AVR_Attachment_Validation_Rules__c objRule, Map<Id, List<SObject>> mapObjs) {
        Set<Id> setRecIds = mapObjs.keySet();
        String strSoql = 'SELECT Id FROM ' + objRule.SObject__c + ' WHERE Id IN :setRecIds';
        if (!String.isEmpty(objRule.SOQL_WHERE_Clause__c)) {
            strSoql += ' AND ' + objRule.SOQL_WHERE_Clause__c;
        }

        for (List<SObject> lstErrs : Database.query(strSoql)) {
            for (SObject e : lstErrs) {
                for (SObject o : mapObjs.get(e.Id)) {
                    o.addError(objRule.Error_Message__c);
                }
            }
        }
    }

}